// Shim: re-exports from @/dom-events for backwards-compatibility.
export {
  DOMCustomEventHandler,
  DOMCustomEventHandler as QueryCustomEventHandler,
  type EventTypes,
  type CustomEventListener,
  type CustomEventListenerOptions,
  type CustomEventHandlerData,
  type CustomEventAddHandler,
  type CustomEventRemoveHandler,
  type CustomEventHandlerResult,
  type ComplexCustomEventHandlerResult,
  type CustomEventHandlerCommon,
  type CustomEventHandler,
  type ComplexCustomEventHandler,
  type CustomEventFactory,
  type CreateCustomEventOptions,
  type AddCustomEventOptions,
  type RemoveCustomEventOptions,
} from '@/dom-events/custom-events';
